CREATE TABLE CLIENTS (
  ID_CLIENT      INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME_CLIENT    VARCHAR(155)    NOT NULL,
  ADDRESS_CLIENT VARCHAR(255)    NOT NULL,
  PHONE_CLIENT   VARCHAR(11)     NOT NULL
);