CREATE TABLE GOODS (
  ID_GOOD          INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NAME_GOOD        VARCHAR(255)    NOT NULL,
  DESCRIPTION_GOOD VARCHAR(255)    NOT NULL,
  PRICE_GOOD       DOUBLE          NOT NULL
);