CREATE TABLE GOODS (
  ID_GOOD          INT PRIMARY KEY NOT NULL,
  NAME_GOOD        VARCHAR(255)    NOT NULL,
  DISCRIPTION_GOOD VARCHAR(255)    NOT NULL,
  PRICE_GOOD       DOUBLE          NOT NULL
);